TravelAgency/Controllers/CityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelAgency.Data.Base;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    [Authorize]
    public class CityController : Controller
    {
        private readonly IEntityBaseRepository<City> _rep;

        public CityController(IEntityBaseRepository<City> rep)
        {
            _rep = rep;
        }

        public async Task<IActionResult> Index()
        {
            var allCities = await _rep.GetAllAsync();
            return View(allCities);
        }

        #region Добавление

        public IActionResult Create() 
        { 
            return View(new City());
        }

        [HttpPost]
        public async Task<IActionResult> Create(City city)
        {
            if (city == null)
            {
                return View(city);
            }
            else
            {
                await _rep.AddAsync(city);
                return RedirectToAction(nameof(Index));
            }
        }

        #endregion

        #region Просмотр элемента

        public async Task<IActionResult> Details(int id)
        {
            var item = await _rep.GetByIdAsync(id);

            if(item == null) return View("Empty");

            return View(item);
        }

        #endregion

        #region Редактирование  

        public async Task<IActionResult> Edit(int id)
        {
            var item = await _rep.GetByIdAsync(id);

            if (item == null) return View("Empty");

            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(City city)
        {
            if (!ModelState.IsValid)
            {
                return View(city);
            }
            else
            {
                await _rep.UpdateAsync(city);
                return RedirectToAction(nameof(Index));
            }
        }

        #endregion

        #region Удаление

        public async Task<IActionResult> Delete(int id)
        {
            var item = await _rep.GetByIdAsync(id);

            if (item == null) return View("Empty");

            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteItem(int id)
        {
            var item = await _rep.GetByIdAsync(id);
            if (item == null) return View("Empty");

            await _rep.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

TravelAgency/Controllers/HotelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System.Linq;
using TravelAgency.Data;
using TravelAgency.Data.Repository.InterfacesRepo;
using TravelAgency.Data.SelectListItems;
using TravelAgency.Data.ViewModels;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    [Authorize]
    public class HotelController : Controller
    {
        private readonly IHotelRepository _hotelRepository;

        public HotelController(IHotelRepository rep)
        {
            _hotelRepository = rep;
        }

        public async Task<IActionResult> Index()
        {
            var items = await _hotelRepository.GetAllAsync();
            return View(items);
        }

        #region Добавление

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var hotel = await _hotelRepository.GetByIdAsync(null);

            ViewBag.HotelStarRating = hotel.ListHotelStarRating;
            ViewBag.MealType = hotel.ListMealTypes;
            ViewBag.HotelFacility = hotel.HotelFacility;
            ViewBag.RoomAmenity = hotel.RoomAmenity;
            ViewBag.City = hotel.ListCities;
            return View(hotel.Hotel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Hotel item, int[] hotelFacility, int[] roomAmenity)
        {   
            if (item == null)
            {
                return View(item);
            }
            else
            {
                await _hotelRepository.AddAsync(item, hotelFacility, roomAmenity);
                return RedirectToAction(nameof(Index));
            }
        }

        #endregion

        #region Просмотр элемента

        public async Task<IActionResult> Details(int id)
        {
            var item = await _hotelRepository.GetByIdAsync(id);

            if (item.Hotel == null) return View("Empty");

            return View(item.Hotel);
        }

        #endregion

        #region Редактирование  

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var hotel = await _hotelRepository.GetByIdAsync(id);
        
            if (hotel.Hotel == null) return View("Empty");

            ViewBag.HotelStarRating = hotel.ListHotelStarRating;
            ViewBag.MealType = hotel.ListMealTypes;
            ViewBag.HotelFacility = hotel.HotelFacility!;
            ViewBag.RoomAmenity = hotel.RoomAmenity!;
            ViewBag.City = hotel.ListCities;

            return View(hotel.Hotel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Hotel item, int[] hotelFacility, int[] roomAmenity)
        {
                await _hotelRepository.UpdateAsync(item, hotelFacility, roomAmenity);
                return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Удаление

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _hotelRepository.GetByIdAsync(id);

            if (item.Hotel == null) return View("Empty");

            return View(item.Hotel);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteItem(int id)
        {
            var item = await _hotelRepository.GetByIdAsync(id);
            if (item == null) return View("Empty");

            await _hotelRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        #endregion

        
    }
}

TravelAgency/Controllers/MealTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelAgency.Data.Base;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    [Authorize]
    public class MealTypeController : Controller
    {
        private readonly IEntityBaseRepository<MealType> _rep;

        public MealTypeController(IEntityBaseRepository<MealType> rep)
        {
            _rep = rep;
        }

        public async Task<IActionResult> Index()
        {
            var items = await _rep.GetAllAsync();
            return View(items);
        }

        #region Добавление

        public IActionResult Create()
        {
            return View(new MealType());
        }

        [HttpPost]
        public async Task<IActionResult> Create(MealType item)
        {
            if (item == null)
            {
                return View(item);
            }
            else
            {
                await _rep.AddAsync(item);
                return RedirectToAction(nameof(Index));
            }
        }

        #endregion

        #region Просмотр элемента

        public async Task<IActionResult> Details(int id)
        {
            var item = await _rep.GetByIdAsync(id);

            if (item == null) return View("Empty");

            return View(item);
        }

        #endregion

        #region Редактирование  

        public async Task<IActionResult> Edit(int id)
        {
            var item = await _rep.GetByIdAsync(id);

            if (item == null) return View("Empty");

            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MealType item)
        {
            if (!ModelState.IsValid)
            {
                return View(item);
            }
            else
            {
                await _rep.UpdateAsync(item);
                return RedirectToAction(nameof(Index));
            }
        }

        #endregion

        #region Удаление

        public async Task<IActionResult> Delete(int id)
        {
            var item = await _rep.GetByIdAsync(id);

            if (item == null) return View("Empty");

            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteItem(int id)
        {
            var item = await _rep.GetByIdAsync(id);
            if (item == null) return View("Empty");

            await _rep.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

TravelAgency/Controllers/TourController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelAgency.Data.Repository;
using TravelAgency.Data.Repository.InterfacesRepo;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    [Authorize]
    public class TourController : Controller
    {
        private readonly IWebHostEnvironment _webHost;

        private readonly ITourRepository _repository;

        public TourController(ITourRepository repository, 
                                IWebHostEnvironment webHost)
        {
            _repository = repository;
            _webHost = webHost;

        }
        
        public async Task<IActionResult> Index()
        {
            var items = await _repository.GetAllAsync();
            return View(items);
        }

        #region Добавление

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var tour = await _repository.GetByTourViewModelAsync();

            ViewBag.Hotel = tour.ListHotel;
            ViewBag.IncludedServices = tour.IncludedServices;
            ViewBag.NotIncludedServices = tour.NotIncludedServices;


            return View(tour.Tour);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Tour tour, int[] includedServices, int[] notIncludedServices)
        {
            if (tour == null)
            {
                return View(tour);
            }
            else
            {
                string uniqueFileName = GetUploadedFileName(tour);
                if(uniqueFileName != null) { tour.PhotoUrl = uniqueFileName; }
                
                await _repository.AddAsync(tour, includedServices, notIncludedServices);
                return RedirectToAction(nameof(Index));
            }
        }

        #endregion


        #region Просмотр

        public async Task<IActionResult> Details(int id)
        {
            var item = await _repository.GetByIdAsync(id);

            if (item.Tour == null) return View("Empty");

            return View(item.Tour);
        }

        #endregion


        #region Удаление

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _repository.GetByIdAsync(id);

            if (item.Tour == null) return View("Empty");

            return View(item.Tour);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteItem(int id)
        {
            var item = await _repository.GetByIdAsync(id);
            if (item == null) return View("Empty");

            await _repository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        #endregion


        #region Редактирование  

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var tour = await _repository.GetByIdAsync(id);

            if (tour.Tour == null) return View("Empty");

            ViewBag.Hotel = tour.ListHotel;
            ViewBag.IncludedServices = tour.IncludedServices;
            ViewBag.NotIncludedServices = tour.NotIncludedServices;
            
            return View(tour.Tour);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Tour tour, int[] includedServices, int[] notIncludedServices)
        {
            string uniqueFileName = GetUploadedFileName(tour);
            if (uniqueFileName != null) { tour.PhotoUrl = uniqueFileName; }

            await _repository.UpdateAsync(tour, includedServices, notIncludedServices);
            return RedirectToAction(nameof(Index));
        }

        #endregion


        #region Добавление файла изображения

        private string GetUploadedFileName(Tour tour)
        {
            string? uniqueFileName = null;

            if(tour.TourPhoto != null)
            {
                string uploadsFolder = Path.Combine(_webHost.WebRootPath, "images");
                uniqueFileName = string.Concat(Guid.NewGuid().ToString(),"_",tour.TourPhoto.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    tour.TourPhoto.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        #endregion

    }
}

TravelAgency/Views/Shared/Empty.cshtml
@{
    ViewData["Title"] = "Ненайдено";
}

<h2>Ой... Ничего не найдено</h2>
<br> <br> 
<p>Попробуйте еще раз</p>

TravelAgency/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TravelAgency.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">


    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css">

</head>
<body>

    <div id="wrapper">
        
        <header>
            <i class="bi bi-airplane-engines"></i> ТА "Родина"
            <form name="search" action="#" method="get">
                <input type="text" name="q" placeholder="Поиск..."><button type="submit">Найти</button>
            </form>
        </header>
        
        <nav>
            <ul class="top-menu">
                <li><a style="color: #0077cc;" asp-area="" asp-controller="Home" 
                    asp-action="Index">ГЛАВНАЯ</a>
                </li>
                <li>
                    <a style="color: #0077cc;" asp-area="" asp-controller="Home"
                       asp-action="AboutUs">О НАС</a>
                </li>
                <li>
                    <a style="color: #0077cc;" asp-area="" asp-controller="Home"
                       asp-action="ListServices">УСЛУГИ</a>
                </li>
                <li>
                    <a style="color: #0077cc;" asp-area="" asp-controller="Home"
                       asp-action="Contacts">КОНТАКТЫ</a>
                </li>
                
                @if (SignInManager.IsSignedIn(User))
                {
                    <li name="entrance">
                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button style="color: #0077cc;" id="logout" 
                            type="submit" class="nav-link btn btn-link">ВЫЙТИ</button>
                        </form>
                    </li>                    
                }
                else
                {
                    <li name="entrance"><a style="color: #0077cc;" href="/Identity/Account/Login">ВОЙТИ</a></li>
                }

                @if (SignInManager.IsSignedIn(User))
                {
                    <li><a style="color: #0077cc;" asp-area="" asp-controller="Tour" asp-action="Index">УПРАВЛЕНИЕ</a></li>
                }
                
                @*<partial name="_LoginPartial" />*@

            </ul>
        </nav>
        <div id="heading">
            <h4>Туристическое агенство "Родина"</h4>
        </div>
        
        
    </div>


    <div id="UserHomePage" class="bottom-element">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <footer>
        <div id="footer">
            <div id="twitter">
                <h3>Новости</h3>
                <time datetime="@DateTime.Now.Date.ToString()">@DateTime.Now.ToString()</time>
                <p>
                    В этом месяце скидка 20% на туры в Санкт-Петербург. Что бы узнать подробности акции свяжитесть с нашим консультантом.
                </p>
            </div>
            <div id="sitemap">
                <h3>КАРТА САЙТА</h3>
                <div>
                    <a asp-area="" asp-controller="Home"
                       asp-action="Index">Главная</a>
                    <a asp-area="" asp-controller="Home"
                       asp-action="AboutUs">О нас</a>
                    <a asp-area="" asp-controller="Home"
                       asp-action="ListServices">Услуги</a>
                    <a asp-area="" asp-controller="Home"
                       asp-action="Contacts">Контакты</a>
                </div>
            </div>
            
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
    <script>
        $(document).ready(function () {
            $('.top-menu li').hover(function () {
                $(this).css('background-color', '#29c5e6');
            }, function () {
                $(this).css('background-color', '');
            });
        });
    </script>

</body>
</html>

TravelAgency/Views/Shared/_Layout_2.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TravelAgency.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">


    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css">

</head>

<body>

    <div id="wrapper">
        
        <header>
            <i class="bi bi-airplane-engines"></i> ТА "Родина"
            <form name="search" action="#" method="get">
                <input type="text" name="q" placeholder="Поиск..."><button type="submit">Найти</button>
            </form>
        </header>
        
        <nav>
            <ul class="top-menu">
                <li>
                    <a asp-area="" asp-controller="Home"
                       asp-action="Index">ГЛАВНАЯ</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home"
                       asp-action="AboutUs">О НАС</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home"
                       asp-action="ListServices">УСЛУГИ</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home"
                       asp-action="Contacts">КОНТАКТЫ</a>
                </li>
                <li name="entrance">
                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button id="logout" type="submit" class="nav-link btn btn-link text-dark">ВЫЙТИ</button>
                    </form>
                </li>
            </ul>
        </nav>
        <div id="heading">
            <h4>Туристическое агенство "Родина"</h4>
        </div>
        <aside>
            <nav>
                <ul class="aside-menu">
                    <li><a asp-area="" asp-controller="Tour" asp-action="Index">Туры</a></li>
                    <li><a asp-area="" asp-controller="Hotel" asp-action="Index">Отели</a></li>
                    <li>
                        Справочники
                        <ul class="sub-menu" style="display: none;">
                            <li>
                                <a asp-area="" asp-controller="City" asp-action="Index">
                                    Населенные пункты
                                </a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="HotelStarRating" asp-action="Index">
                                    Звездный рейтинг отеля
                                </a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="MealType" asp-action="Index">
                                    Тип питания
                                </a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="HotelFacility" asp-action="Index">
                                    Услуги отеля
                                </a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="RoomAmenity" asp-action="Index">
                                    Оснащение номера
                                </a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="TravelService" asp-action="Index">
                                    Услуги турагенства
                                </a>
                            </li>
                        </ul>
                    </li>

                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Requests" asp-action="Index">Заявки</a></li>
                    }
                      
                    <li><a asp-area="" asp-controller="Analytics" asp-action="Index">Аналитика</a></li>
                </ul>
            </nav>
        </aside>

        <section class="bottom-element">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </section>
    </div>
    
    <footer>
        <div id="footer">
            <div id="twitter">
                <h3>Новости</h3>
                <time datetime="@DateTime.Now.Date.ToString()">@DateTime.Now.ToString()</time>
                <p>
                    В этом месяце скидка 20% на туры в Санкт-Петербург. Что бы узнать подробности акции свяжитесть с нашим консультантом.
                </p>
            </div>
            <div id="sitemap">
                <h3>КАРТА САЙТА</h3>
                <div>
                    <a asp-area="" asp-controller="Home"
                       asp-action="Index">Главная</a>
                    <a asp-area="" asp-controller="Home"
                       asp-action="AboutUs">О нас</a>
                    <a asp-area="" asp-controller="Home"
                       asp-action="ListServices">Услуги</a>
                    <a asp-area="" asp-controller="Home"
                       asp-action="Contacts">Контакты</a>
                </div>
            </div>
            
        </div>
    </footer>


                                                 @*Скрипты*@


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
    <script>
        $(document).ready(function () {
            $('.top-menu li').hover(function () {
                $(this).css('background-color', '#29c5e6');
            }, function () {
                $(this).css('background-color', '');
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('.aside-menu li').hover(function () {
                $(this).css('color', '#29c5e6');
            }, function () {
                $(this).css('color', '');
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('.aside-menu a').hover(function () {
                $(this).css('color', '#29c5e6');
            }, function () {
                $(this).css('color', '');
            });
        });
    </script>    
    

    <script>
        $(document).ready(function () {
            $('table:not(#requests) tr').hover(function () {
                $(this).css('background-color', '#d4d4d4');
            }, function () {
                $(this).css('background-color', '');
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('li:contains("Справочники")').click(function () {
                $(this).find('.sub-menu').toggle();
            });
        });
    </script>

</body>
</html>